#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : AQ Project Jupyter Book  # The title of the book. Will be placed in the left navbar.
author                      : Wesley Darling, Gyuhyeon Seo, Jae Hee Koh, Ram Mukund Kripa # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : orangeskies.jpeg  # A path to the book logo

execute:
  execute_notebooks: 'off'

only_build_toc_files: true

# TODO: the below should be disabled and instead the sphinx section activated
# after we upgrade to j-book newer than 0.9.1 and its dependencies.  For now
# this gives us the equivalent of html_images fixes, but without version
# conflicts that currently arise from trying to use it.
#parse:
#  myst_extended_syntax: true

# Sphinx section commented out for now as per above todo, will activate it
# later. 

bibtex_bibfiles: 
  - references.bib