name: aqproject
channels:
  - conda-forge
dependencies:
  - ipykernel
  - conda-forge::python=3.9
  - numpy
  - pandas
  - seaborn
  - geopandas
  - Shapely
  - geoplot
  - imageio
  - pytest
  - scipy
  - matplotlib
  - scikit-learn
  - conda-forge::tensorflow
  - pip
  - pip:
    - py-openaq
    - basemap
    - noaa-sdk
