name: aqproject
dependencies:
  - ipykernel
  - python=3.8
  - numpy
  - pandas
  - seaborn
  - geopandas
  - Shapely
  - geoplot
  - imageio
  - pytest
  - scipy
  - matplotlib
  - scikit-learn
  - tensorflow=2.7
  - pip
  - pip:
    - py-openaq
    - basemap
    - noaa-sdk
